// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJxSlwYK-XzQQzlNHV8ZgpeJySRC3IQPc',
    appId: '1:510132482672:web:8a419f77946ae2c934fab5',
    messagingSenderId: '510132482672',
    projectId: 'fireflutter-2',
    authDomain: 'fireflutter-2.firebaseapp.com',
    storageBucket: 'fireflutter-2.appspot.com',
    measurementId: 'G-PQS6B9720X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlr9GF1kAcG-JII1nuhkal4DXrYVBHZPc',
    appId: '1:510132482672:android:ea7edea4c14d8dd034fab5',
    messagingSenderId: '510132482672',
    projectId: 'fireflutter-2',
    storageBucket: 'fireflutter-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApaNLD-z6WW-AqO4cXdRFTUcxrAvmSpeo',
    appId: '1:510132482672:ios:438d34c7deca241634fab5',
    messagingSenderId: '510132482672',
    projectId: 'fireflutter-2',
    storageBucket: 'fireflutter-2.appspot.com',
    iosBundleId: 'com.example.finalExam2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApaNLD-z6WW-AqO4cXdRFTUcxrAvmSpeo',
    appId: '1:510132482672:ios:438d34c7deca241634fab5',
    messagingSenderId: '510132482672',
    projectId: 'fireflutter-2',
    storageBucket: 'fireflutter-2.appspot.com',
    iosBundleId: 'com.example.finalExam2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJxSlwYK-XzQQzlNHV8ZgpeJySRC3IQPc',
    appId: '1:510132482672:web:5e873529ed003e2634fab5',
    messagingSenderId: '510132482672',
    projectId: 'fireflutter-2',
    authDomain: 'fireflutter-2.firebaseapp.com',
    storageBucket: 'fireflutter-2.appspot.com',
    measurementId: 'G-B19Z9HG2YG',
  );
}
